### ISSUE TITLE
[GESSO 5] The design tokens file is not working at all after any changes

### ISSUE THREAD

**Issue by liquilife** [forumone/gesso-theme-wordpress#330] opened 2022-05-10 17:20 UTC
I am unable to reflect any and all changes in the design tokens file into my theme.json and any other styles. I have verified `ddev gesso watch` is working when modifying .scss files. It just silently will not build any new preferences set in `config.design-tokens.yml`. The result is I am perpetually stuck with the default config settings throughout the entire theme. 

The issue persists after restarting ddev. There is no terminal warnings.

**Comment by timnolte** [comment] 2022-05-10 17:29
This is a duplicate of https://github.com/forumone/gesso-wp/issues/329

**Closed as completed** 2022-05-10 18:15 UTC
